# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - marvel-story

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_27b4fc9031dc40f0a45ea1975bfc5e7b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d987c07a49f3434bb7ab405d7a1f276a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_27b4fc9031dc40f0a45ea1975bfc5e7b }}/marvel-story:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'marvel-story'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b9320d632e144f9ac8ee20eda54c713 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_27b4fc9031dc40f0a45ea1975bfc5e7b }}/marvel-story:${{ github.sha }}'
